### ISSUE TITLE
no audio on usb type c headset on cas device

### ISSUE THREAD

**Issue by wshamroukh** [yarpiin/White-Wolf-UMI-UNI#1]
I have installed your latest kernel and I found out that there is no sound when I connect a wired headset. While watching youtube, if i connect the wired headset, the video will start shuttering and if i disconnect the wired headset, the device hangs and then reboots. I have collected adb logcat logs while connecting the usb headset... I have looked at the logs, i see some errors related to adsprpcd. catlog can be found here: [https://hastebin.com/inayufidaf.yaml](https://hastebin.com/inayufidaf.yaml)
I am using Cherish OS 4.3 A13 on my MI 10 Ultra (cas)

**Comment by wshamroukh** [comment]
not related to kernel

**Comment by kanmurimori** [comment]
@wshamroukh how did you fix it?

**Comment by wshamroukh** [comment]
> @wshamroukh how did you fix it?

here is the fix https://github.com/PixelExperience/android-issues/issues/3746#issuecomment-1369362727
